pub const WINDOW_WIDTH: f32 = 1400.;
pub const WINDOW_HEIGHT: f32 = 800.;

pub const UI_VIEWPORT_WIDTH: f32 = 400.;
pub const UI_VIEWPORT_HEIGHT: f32 = WINDOW_HEIGHT;

pub const GAMELOG_VIEWPORT_WIDTH: f32 = WINDOW_WIDTH - UI_VIEWPORT_WIDTH;
pub const GAMELOG_VIEWPORT_HEIGHT: f32 = 200.;

pub const GAME_VIEWPORT_WIDTH: f32 = WINDOW_WIDTH - UI_VIEWPORT_WIDTH;
pub const GAME_VIEWPORT_HEIGHT: f32 = WINDOW_HEIGHT - GAMELOG_VIEWPORT_HEIGHT; 

pub const SPRITE_SIZE: f32 = 64.;
pub const SPRITE_SCALE: f32 = SPRITE_SIZE / 8.;

pub const MOVE_SPEED: f32 = 500.;
